server:
  port: 8888
spring:
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'